# Generated by Django 5.2.17 on 2026-09-16 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionBano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('bano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='sistema.bano')),
                ('trabajador', models.ForeignKey(limit_choices_to={'rol': 'TRABAJADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_banos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('bano',), name='un_bano_una_asignacion_activa'), models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('trabajador',), name='un_trabajador_una_asignacion_activa')],
            },
        ),
    ]
