# Generated by Django 5.2.17 on 2026-09-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_asignacionbano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(default='Umbral de uso alcanzado', max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('ATENDIDA', 'Atendida')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='sistema.bano')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
