# Generated by Django 5.2.17 on 2026-09-16 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alerta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervencionLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='intervencion', to='sistema.alerta')),
                ('bano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervenciones_limpieza', to='sistema.bano')),
                ('trabajador', models.ForeignKey(limit_choices_to={'rol': 'TRABAJADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='intervenciones_limpieza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
