# Generated by Django 5.2.17 on 2026-09-16 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_intervencionlimpieza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencionlimpieza',
            name='trabajador',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'rol': 'TRABAJADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='intervenciones_limpieza', to=settings.AUTH_USER_MODEL),
        ),
    ]
