# Generated by Django 5.2.17 on 2026-09-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_intervencionlimpieza_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencionlimpieza',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias_limpieza/%Y/%m/%d/'),
        ),
    ]
