# Generated by Django 5.2.17 on 2026-09-17 23:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_intervencionlimpieza_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('fecha_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('origen', models.CharField(choices=[('SIMULADO', 'Simulado'), ('VISION', 'Visión artificial')], default='SIMULADO', max_length=20)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('bano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_conteo', to='sistema.bano')),
            ],
            options={
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
